### ISSUE TITLE
Documentation link doesn't work

### ISSUE THREAD

**Issue by mgedmin** [simplistix/buildout-tox#1]
README.txt refers me to http://packages.python.org/buildout_tox, which gives a 404 error.

http://pypi.python.org/pypi/buildout-tox links to http://packages.python.org/buildout-tox/use.html which is also missing.

**Comment by cjw296** [comment]
buildout-tox is dead, just use Tox ;-)

For an example, see:

https://github.com/Simplistix/testfixtures/blob/master/buildout.cfg
https://github.com/Simplistix/testfixtures/blob/master/setup.py
https://github.com/Simplistix/testfixtures/blob/master/tox.ini

...in use here:

http://jenkins.simplistix.co.uk/job/testfixtures-tox/

**Comment by mgedmin** [comment]
Your comment would make a fine replacement for the current README then ;-)

(I looked at the Tox documentation, saw _zero_ examples mentioning Buildout, vaguely remembered your struggles with setuptools extras and similar questions on the list, googled for "using tox with buildout" and found this promisingly-looking package with a decoy README.)

**Comment by cjw296** [comment]
Okay, updated all the broken bits now ;-)
